"""empty message

Revision ID: 038b50daccb4
Revises: dcc5b7602c87
Create Date: 2020-05-13 02:38:29.540818

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '038b50daccb4'
down_revision = 'dcc5b7602c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recommend', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('recommend')
        batch_op.drop_column('highlight')

    # ### end Alembic commands ###
