"""empty message

Revision ID: 14970b8f74f9
Revises: 0dbd712920d2
Create Date: 2020-05-10 21:27:48.342047

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14970b8f74f9'
down_revision = '0dbd712920d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_times', sa.DateTime(), nullable=True))
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('create_times')

    # ### end Alembic commands ###
