"""empty message

Revision ID: 327456caa799
Revises: 14970b8f74f9
Create Date: 2020-05-10 21:29:00.865146

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '327456caa799'
down_revision = '14970b8f74f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'front_user', ['author_id'], ['id'])
        batch_op.drop_column('create_times')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_times', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('create_time')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
