"""empty message

Revision ID: ae95265b4120
Revises: dd13003d7992
Create Date: 2020-05-13 02:26:01.466839

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ae95265b4120'
down_revision = 'dd13003d7992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recommend', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('recommend')
        batch_op.drop_column('highlight')

    # ### end Alembic commands ###
