"""empty message

Revision ID: dcc5b7602c87
Revises: ae95265b4120
Create Date: 2020-05-13 02:37:32.115770

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dcc5b7602c87'
down_revision = 'ae95265b4120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('front_user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('front_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
